-- Migration script to add cities table and update cinemas table

-- 1. Create cities table
CREATE TABLE cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(10) UNIQUE,
    country VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

-- 2. Insert some sample cities
INSERT INTO cities (name, code, country, is_active) VALUES
('Ho Chi Minh City', 'HCM', 'Vietnam', TRUE),
('Ha Noi', 'HN', 'Vietnam', TRUE),
('Da Nang', 'DN', 'Vietnam', TRUE),
('Can Tho', 'CT', 'Vietnam', TRUE),
('Hai Phong', 'HP', 'Vietnam', TRUE),
('Nha Trang', 'NT', 'Vietnam', TRUE),
('Vung Tau', 'VT', 'Vietnam', TRUE),
('Hue', 'HU', 'Vietnam', TRUE),
('Quy Nhon', 'QN', 'Vietnam', TRUE),
('Bien Hoa', 'BH', 'Vietnam', TRUE);

-- 3. Add city_id column to cinemas table
ALTER TABLE cinemas ADD COLUMN city_id BIGINT;

-- 4. Update existing cinemas to use city_id instead of city string
-- This is a sample mapping - you may need to adjust based on your actual data
UPDATE cinemas SET city_id = (SELECT id FROM cities WHERE name = 'Ho Chi Minh City' LIMIT 1) 
WHERE city = 'Ho Chi Minh City' OR city = 'TP.HCM' OR city = 'Ho Chi Minh';

UPDATE cinemas SET city_id = (SELECT id FROM cities WHERE name = 'Ha Noi' LIMIT 1) 
WHERE city = 'Ha Noi' OR city = 'Hanoi';

UPDATE cinemas SET city_id = (SELECT id FROM cities WHERE name = 'Da Nang' LIMIT 1) 
WHERE city = 'Da Nang';

UPDATE cinemas SET city_id = (SELECT id FROM cities WHERE name = 'Can Tho' LIMIT 1) 
WHERE city = 'Can Tho';

UPDATE cinemas SET city_id = (SELECT id FROM cities WHERE name = 'Hai Phong' LIMIT 1) 
WHERE city = 'Hai Phong';

UPDATE cinemas SET city_id = (SELECT id FROM cities WHERE name = 'Nha Trang' LIMIT 1) 
WHERE city = 'Nha Trang';

UPDATE cinemas SET city_id = (SELECT id FROM cities WHERE name = 'Vung Tau' LIMIT 1) 
WHERE city = 'Vung Tau';

UPDATE cinemas SET city_id = (SELECT id FROM cities WHERE name = 'Hue' LIMIT 1) 
WHERE city = 'Hue';

UPDATE cinemas SET city_id = (SELECT id FROM cities WHERE name = 'Quy Nhon' LIMIT 1) 
WHERE city = 'Quy Nhon';

UPDATE cinemas SET city_id = (SELECT id FROM cities WHERE name = 'Bien Hoa' LIMIT 1) 
WHERE city = 'Bien Hoa';

-- 5. Set default city for any remaining cinemas without city_id
UPDATE cinemas SET city_id = (SELECT id FROM cities WHERE name = 'Ho Chi Minh City' LIMIT 1) 
WHERE city_id IS NULL;

-- 6. Make city_id NOT NULL and add foreign key constraint
ALTER TABLE cinemas ALTER COLUMN city_id SET NOT NULL;
ALTER TABLE cinemas ADD CONSTRAINT fk_cinemas_city FOREIGN KEY (city_id) REFERENCES cities(id);

-- 7. Drop the old city column
ALTER TABLE cinemas DROP COLUMN city;
